### ISSUE TITLE
URLTagBinding inserting clipboard text in wrong location.`

### ISSUE THREAD

**Issue by curtisrutland** [curtisrutland/DIC-Editor-Shortcuts#4]
Steps to reproduce:
1. Copy the following to your clipboard: `https://www.google.com/`
2. Browse to any DIC thread, click on the Fast Reply box
3. Enter text into the fast reply box:  
   ![image](https://f.cloud.github.com/assets/660493/1075011/e1942f50-14c5-11e3-8f59-901990f62a90.png)
4. Select "test":  
   ![image](https://f.cloud.github.com/assets/660493/1075015/f902ca5c-14c5-11e3-820f-c63ad20be96d.png)
5. Press Ctrl+L

Expected result: selected text is surrounded by URL tags with clipboard contents set as target url.

Actual result:  
![image](https://f.cloud.github.com/assets/660493/1075032/54a96596-14c6-11e3-9cf6-d07ea454865d.png)

_Note_: I had trouble reproducing this correctly. It seems like things copied from other tabs aren't always pasted when pressing Ctrl+L. We might need to look into our clipboarding a bit more.

**Comment by ryan-beckett** [comment]
I take it what you said on DIC was that we could push any bug fixes, but to make pull requests for new functionality so we can review and agree on everything. If you have any issues with this, let me know.

**Comment by curtisrutland** [comment]
Yeah, bug fixes are fine. Feel free to push pretty much anything you want, as long as it's not a big breaking change.
