### ISSUE TITLE
Tag highlighting and editing

### ISSUE THREAD

**Issue by CasiOo** [curtisrutland/DIC-Editor-Shortcuts#7]
I really like this feature in the Visual Studio 2012 editor.
When you have the cursor in a tag, it highlights the start and end tag. It makes it easier to see start and end.
They also made it possible to edit one tag, and the other connected tag will be edited along. Like, if I edit the start tag 'div' to 'li' then the end tag will be changed into '/li' by the editor

Highlighting tags will definitely be something I'll look more into the next couple of days :)

**Comment by curtisrutland** [comment]
Love that idea. When you make an issue that you're going to work on, or when you want to start working on an open issue, go ahead and assign it to yourself. That should help keep us from duplicating any work.

**Comment by ryan-beckett** [comment]
Great idea! I would love to see something that.

**Comment by CasiOo** [comment]
Just wanted to let you guys know that I'm still here :)
I've started working on the above issue. Finally I have some free time from work with no overtime. Lets push some life into this project once more!
